# Generated by Django 5.2.13 on 2026-04-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(verbose_name=25)),
                ('last_name', models.CharField(verbose_name=25)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField(verbose_name=10)),
            ],
        ),
    ]
