# Generated by Django 5.2.13 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='BlogModel',
        ),
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ['-date_uploaded']},
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='body',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
