# Generated by Django 5.2.13 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_blog_and_update_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Let’s talk', max_length=100)),
                ('intro_text', models.TextField(default='Reach out if you want to discuss school operations, student support, or a new campus project.')),
                ('email', models.EmailField(default='deena.admin@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+1 (000) 123-4567', max_length=30)),
                ('whatsapp_number', models.CharField(default='10001234567', max_length=20)),
                ('whatsapp_label', models.CharField(default='WhatsApp', max_length=50)),
                ('whatsapp_help_text', models.CharField(default='Chat instantly', max_length=80)),
                ('instagram_url', models.URLField(default='https://www.instagram.com')),
                ('linkedin_url', models.URLField(default='https://www.linkedin.com')),
                ('youtube_url', models.URLField(default='https://www.youtube.com')),
            ],
            options={
                'verbose_name': 'Contact info',
                'verbose_name_plural': 'Contact info',
            },
        ),
    ]
