# Generated by Django 5.2.13 on 2026-04-17

from django.db import migrations, models
from django.db.models import deletion
from django.utils.text import slugify


def populate_blog_slugs(apps, schema_editor):
    BlogModel = apps.get_model('web', 'BlogModel')
    for post in BlogModel.objects.all():
        if not post.slug:
            base_slug = slugify(post.title) or 'blog-post'
            slug = base_slug
            counter = 1
            while BlogModel.objects.filter(slug=slug).exclude(pk=post.pk).exists():
                slug = f'{base_slug}-{counter}'
                counter += 1
            post.slug = slug
            post.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=deletion.CASCADE, related_name='comments', to='web.blogmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(populate_blog_slugs, migrations.RunPython.noop),
    ]
